name: Jenkins Agent Packer

strategy:
  matrix:
    Ubuntu:
      os: Ubuntu
      templatePath: jenkins-agent-ubuntu.pkr.hcl
    CentOS:
      os: CentOS
      templatePath: jenkins-agent-centos-7.9-x86_64.pkr.hcl

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
  - task: riezebosch.Packer.PackerTool.PackerTool@0
    displayName: 'Install Packer'
    inputs:
      version: 1.7.4

  - task: riezebosch.Packer.Packer.Packer@1
    displayName: 'Validate Jenkins Agent for $(os)'
    inputs:
      templatePath: $(templatePath)
      command: validate
      azureSubscription: dts-management-prod-intsvc


  - task: riezebosch.Packer.Packer.Packer@1
    displayName: 'PR Build'
    condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))
    inputs:
      templatePath: $(templatePath)
      variables: |
          jenkins_ssh_key=$(JENKINS_SSH_KEY)
      command: build
      azureSubscription: dts-management-prod-intsvc
      options: --only=azure-arm.azure-no-sig

  - task: riezebosch.Packer.Packer.Packer@1
    displayName: 'Build and publish'
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/master'))
    inputs:
      templatePath: $(templatePath)
      variables: |
          jenkins_ssh_key=$(JENKINS_SSH_KEY)
      command: build
      azureSubscription: dts-management-prod-intsvc
      options: --only=azure-arm.azure-sig-publish
