name: Jenkins Agent Packer

stages:
  - stage: Validate
    pool:
      vmImage: 'ubuntu-18.04'
    jobs:
      - job: Validate
        steps:
          - checkout: self
          - task: riezebosch.Packer.PackerTool.PackerTool@0
            displayName: 'Install Packer'
            inputs:
              version: 1.7.4

          - task: riezebosch.Packer.Packer.Packer@1
            displayName: 'Validate Jenkins Agent for Ubuntu'
            inputs:
              templatePath: jenkins-agent-ubuntu.pkr.hcl
              command: validate
              azureSubscription: dts-management-prod-intsvc

          - task: riezebosch.Packer.Packer.Packer@1
            displayName: 'Validate Jenkins Agent for CentOs'
            inputs:
              templatePath: jenkins-agent-centos-7.9-x86.pkr.hcl
              command: validate
              azureSubscription: dts-management-prod-intsvc

  - stage: Build Ubuntu
    pool:
      vmImage: 'ubuntu-18.04'
    jobs:
      - job: Build
        steps:
          - task: riezebosch.Packer.Packer.Packer@1
            displayName: 'Build Jenkins Agent for Ubuntu'
            condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/master'))
            inputs:
              templatePath: jenkins-agent-ubuntu.pkr.hcl
              variables: |
                  jenkins_ssh_key=$(JENKINS_SSH_KEY)
              command: build
              azureSubscription: dts-management-prod-intsvc

  - stage: Build CentOS
    depends: []
    pool:
      vmImage: 'ubuntu-18.04'
    jobs:
      - job: Build
        steps:
          - task: riezebosch.Packer.Packer.Packer@1
            displayName: 'Build Jenkins Agent for CentOs'
            condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/master'))
            inputs:
              templatePath: jenkins-agent-centos-7.9-x86_64.pkr.hcl
              variables: |
                  jenkins_ssh_key=$(JENKINS_SSH_KEY)
              command: build
              azureSubscription: dts-management-prod-intsvc
